// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJiQ4ePAThLyuiZZWTAAfJQBKvtH2zjt4',
    appId: '1:508586114616:web:d539bd2569560cd6e870cd',
    messagingSenderId: '508586114616',
    projectId: 'threelinediary-9b7e4',
    authDomain: 'threelinediary-9b7e4.firebaseapp.com',
    storageBucket: 'threelinediary-9b7e4.appspot.com',
    measurementId: 'G-N9ZFEC19X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPkKVGtg0TCzu12z5lJx3oSd1WHoKsIzQ',
    appId: '1:508586114616:android:296e8344d1fbde03e870cd',
    messagingSenderId: '508586114616',
    projectId: 'threelinediary-9b7e4',
    storageBucket: 'threelinediary-9b7e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPFAptzC8aP4f_sP-W64PpnsDKv0PVSoA',
    appId: '1:508586114616:ios:41c36b404cbebb02e870cd',
    messagingSenderId: '508586114616',
    projectId: 'threelinediary-9b7e4',
    storageBucket: 'threelinediary-9b7e4.appspot.com',
    iosBundleId: 'com.example.threeLineDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPFAptzC8aP4f_sP-W64PpnsDKv0PVSoA',
    appId: '1:508586114616:ios:9fc2cb94258c8fcfe870cd',
    messagingSenderId: '508586114616',
    projectId: 'threelinediary-9b7e4',
    storageBucket: 'threelinediary-9b7e4.appspot.com',
    iosBundleId: 'com.example.threeLineDiary.RunnerTests',
  );
}
